### ISSUE TITLE
Thank you for this app.

### ISSUE THREAD

**Issue by chwar** [locomorange/ble-midi-connect#1]
Hi,

I just wanted to say a quick thanks for developing this app. I have been trying to use my Millenium/Medeli e-piano with its built-in bluetooth on windows for years without any success. Out of curiosity I checked again to see if I could get it to work magically today, and I found this app. It worked out of the box in seconds. Immediately bought it :)

**Comment by locomorange** [comment]
Thank you for your comment.
It's very encouraging!
